[phases.setup]
nixPkgs = ["nodejs-18_x", "python3", "make", "gcc"]

[phases.install]
cmds = [
  "cd backend && npm install",
  "cd backend && npm prune --production"
]

[start]
cmd = "cd backend && node server.js"

